return {}
-- return {
-- 	"saghen/blink.cmp",
-- 	dependencies = { "rafamadriz/friendly-snippets", "onsails/lspkind-nvim", "nvim-tree/nvim-web-devicons" },
--
-- 	version = "*",
-- 	event = "InsertEnter",
--
-- 	---@module 'blink.cmp'
-- 	---@type blink.cmp.Config
-- 	opts = {
--
-- 		keymap = { preset = "super-tab" },
--
-- 		appearance = {
-- 			-- 'mono' (default) for 'Nerd Font Mono' or 'normal' for 'Nerd Font'
-- 			-- Adjusts spacing to ensure icons are aligned
-- 			nerd_font_variant = "mono",
-- 		},
--
-- 		-- (Default) Only show the documentation popup when manually triggered
-- 		completion = {
-- 			documentation = { auto_show = true, auto_show_delay_ms = 200 },
-- 			menu = {
-- 				draw = {
-- 					components = {
-- 						kind_icon = {
-- 							text = function(ctx)
-- 								local lspkind = require("lspkind")
-- 								local icon = ctx.kind_icon
-- 								if vim.tbl_contains({ "Path" }, ctx.source_name) then
-- 									local dev_icon, _ = require("nvim-web-devicons").get_icon(ctx.label)
-- 									if dev_icon then
-- 										icon = dev_icon
-- 									end
-- 								else
-- 									icon = lspkind.symbolic(ctx.kind, {
-- 										mode = "symbol",
-- 									})
-- 								end
--
-- 								return icon .. ctx.icon_gap
-- 							end,
--
-- 							-- Optionally, use the highlight groups from nvim-web-devicons
-- 							-- You can also add the same function for `kind.highlight` if you want to
-- 							-- keep the highlight groups in sync with the icons.
-- 							highlight = function(ctx)
-- 								local hl = ctx.kind_hl
-- 								if vim.tbl_contains({ "Path" }, ctx.source_name) then
-- 									local dev_icon, dev_hl = require("nvim-web-devicons").get_icon(ctx.label)
-- 									if dev_icon then
-- 										hl = dev_hl
-- 									end
-- 								end
-- 								return hl
-- 							end,
-- 						},
-- 					},
-- 				},
-- 			},
-- 		},
--
-- 		sources = {
-- 			default = { "lsp", "path", "snippets", "buffer" },
-- 		},
--
-- 		fuzzy = { implementation = "prefer_rust_with_warning" },
-- 	},
-- 	opts_extend = { "sources.default" },
-- }
